package Comexception.day11;

public class ExceptionHandlingDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		try {
			int[]arr = new int[5];//length = 5,0-4
			arr[5]=10;
		   int a = 20/0;
		
		}
		catch(ArthimaticException ex) {

	     	
		Catch (ArrayInexOutOfBoundsException e) {
		
		}

	   System.out.println("After exception");
	   
	//   finally { 
	//	   System.out.println(After exception in the finally black");
	   }
		   
	} 
	

